name: Docker Build and Push

on:
  push:
    branches: [master]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create a tag
        id: image_tag
        run: echo "IMAGE_TAG=CD-$(date +%Y%m%d%H%M)-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Login to Github Repository
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/vaynerakawalo/${{ github.event.repository.name }}:${{ steps.image_tag.outputs.IMAGE_TAG }}
            ghcr.io/vaynerakawalo/${{ github.event.repository.name }}:latest
